---
openapi: 3.0.3
info:
  version: "1.0.0"
  title: "Dummy Service"
paths:
  /:
    get:
      operationId: "get_root"
      responses:
        "200":
          description: "OK"
          content:
            text/plain: { }
